apiVersion: v1
kind: ConfigMap
metadata:
  name: config-env
data:
  MAIL_DOMAIN: nextcloud.com
  MAIL_FROM_ADDRESS: no-reply
  POSTGRES_DB: nextcloud
  POSTGRES_HOST: nextcloud-database
  POSTGRES_USER: nextcloud
  REDIS_HOST: nextcloud-redis
  REDIS_HOST_PORT: "6379"
  SMTP_AUTHTYPE: PLAIN
  SMTP_HOST: nextcloud-mail-server
  SMTP_PORT: "1025"

---

apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=

---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-web-service
spec:
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud-web
          image: nextcloud:30-apache
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: config-env
            - secretRef:
                name: postgresql-secret

---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-redis
spec:
  selector:
    app: nextcloud-redis
  ports:
    - port: 6379
      targetPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-redis
  template:
    metadata:
      labels:
        app: nextcloud-redis
    spec:
      containers:
        - name: nextcloud-redis
          image: redis:7.4.1-bookworm
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: config-env
            - secretRef:
                name: postgresql-secret

---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-database
spec:
  selector:
    app: nextcloud-database
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-database
  template:
    metadata:
      labels:
        app: nextcloud-database
    spec:
      containers:
        - name: nextcloud-database
          image: postgres:17-bookworm
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgre-data
              mountPath: /var/lib/postgresql/data
          envFrom:
            - configMapRef:
                name: config-env
            - secretRef:
                name: postgresql-secret
      volumes:
        - name: postgre-data
          hostPath:
            path: /data/postgre-data
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mail-server
spec:
  selector:
    app: nextcloud-mail
  ports:
  - port: 1025
    targetPort: 1025

---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mail-server-ui
spec:
  selector:
    app: nextcloud-mail
  ports:
  - port: 1080
    targetPort: 1080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-mail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcloud-mail
  template:
    metadata:
      labels:
        app: nextcloud-mail
    spec:
      containers:
      - name: nextcloud-mail
        image: maildev/maildev:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 1080
        - containerPort: 1025
